In [19]:
student = {'first': ['alter','shirin','qiqi','ozge','hisam','chia'],
           'last':['gudu','mony','tai','bisgin','gudu','gudu'],
           'email':['alter_gudu12@gmail.com','shirinmony@gmail.com','qiqi34@yahoo.com','bisginozge@gmail.com','hismgudu@gmail.com','chiagudu@gmail.com'],
           'matri. num':['10243','50678','76545','32145','67856','76589']}

In [20]:
import pandas as pd

In [21]:
student_df= pd.DataFrame(student)
student_df

    first    last                   email matri. num
0   alter    gudu  alter_gudu12@gmail.com      10243
1  shirin    mony    shirinmony@gmail.com      50678
2    qiqi     tai        qiqi34@yahoo.com      76545
3    ozge  bisgin    bisginozge@gmail.com      32145
4   hisam    gudu      hismgudu@gmail.com      67856
5    chia    gudu      chiagudu@gmail.com      76589

In [22]:
student_df.sort_values(by= 'last', ascending= False)

    first    last                   email matri. num
2    qiqi     tai        qiqi34@yahoo.com      76545
1  shirin    mony    shirinmony@gmail.com      50678
0   alter    gudu  alter_gudu12@gmail.com      10243
4   hisam    gudu      hismgudu@gmail.com      67856
5    chia    gudu      chiagudu@gmail.com      76589
3    ozge  bisgin    bisginozge@gmail.com      32145

In [23]:
student_df.sort_values(by= ['last'] , ascending= False)

    first    last                   email matri. num
2    qiqi     tai        qiqi34@yahoo.com      76545
1  shirin    mony    shirinmony@gmail.com      50678
0   alter    gudu  alter_gudu12@gmail.com      10243
4   hisam    gudu      hismgudu@gmail.com      67856
5    chia    gudu      chiagudu@gmail.com      76589
3    ozge  bisgin    bisginozge@gmail.com      32145

In [27]:
student_df.sort_values(by= ['last','first'] , ascending= [False,True], inplace= True) #first column is in descending order and second column is in ascending order

In [28]:
student_df

    first    last                   email matri. num
2    qiqi     tai        qiqi34@yahoo.com      76545
1  shirin    mony    shirinmony@gmail.com      50678
0   alter    gudu  alter_gudu12@gmail.com      10243
5    chia    gudu      chiagudu@gmail.com      76589
4   hisam    gudu      hismgudu@gmail.com      67856
3    ozge  bisgin    bisginozge@gmail.com      32145

In [30]:
student_df.sort_index()

    first    last                   email matri. num
0   alter    gudu  alter_gudu12@gmail.com      10243
1  shirin    mony    shirinmony@gmail.com      50678
2    qiqi     tai        qiqi34@yahoo.com      76545
3    ozge  bisgin    bisginozge@gmail.com      32145
4   hisam    gudu      hismgudu@gmail.com      67856
5    chia    gudu      chiagudu@gmail.com      76589

In [31]:
student_df['last'].sort_values()

3    bisgin
0      gudu
5      gudu
4      gudu
1      mony
2       tai
Name: last, dtype: object

In [32]:
ds= pd.read_csv('D:\Data Analysis Project\survey_data\survey_results_public.csv', index_col='ResponseId')
schema_ds= pd.read_csv('D:\Data Analysis Project\survey_data\survey_results_schema.csv', index_col='qname')

In [33]:
pd.set_option('display.max_columns',80)
pd.set_option('display.max_rows',80)

In [34]:
ds.head()

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [41]:
ds.sort_values(by='Country',ascending=False,inplace=True) #descending order
#OR
ds.sort_values(by='Country',ascending=False,inplace=True) #ascending order

ds['Country'].head(50)

ResponseId
46152    Zimbabwe
57743    Zimbabwe
44771    Zimbabwe
66478    Zimbabwe
56764    Zimbabwe
68960    Zimbabwe
38746    Zimbabwe
46049    Zimbabwe
46673    Zimbabwe
35586    Zimbabwe
71358    Zimbabwe
44536    Zimbabwe
31003    Zimbabwe
24120    Zimbabwe
19594    Zimbabwe
45312    Zimbabwe
30291    Zimbabwe
71980    Zimbabwe
27470    Zimbabwe
64032    Zimbabwe
52824    Zimbabwe
43528    Zimbabwe
36078    Zimbabwe
4719     Zimbabwe
42449    Zimbabwe
59418    Zimbabwe
72145    Zimbabwe
25845    Zimbabwe
30391    Zimbabwe
25819    Zimbabwe
3150       Zambia
33910      Zambia
53578      Zambia
68826      Zambia
71737      Zambia
52282      Zambia
19021      Zambia
54532      Zambia
58550      Zambia
32505      Zambia
56594      Zambia
34595      Zambia
63276      Zambia
17066      Zambia
52509      Zambia
28334      Zambia
25825      Zambia
27561      Zambia
65120      Zambia
36262      Zambia
Name: Country, dtype: object

In [43]:

ds[['Country', 'ConvertedCompYearly']].head(50)

             Country  ConvertedCompYearly
ResponseId
46152       Zimbabwe                  NaN
57743       Zimbabwe                  NaN
44771       Zimbabwe                  NaN
66478       Zimbabwe              10000.0
56764       Zimbabwe                  NaN
68960       Zimbabwe                  NaN
38746       Zimbabwe                  NaN
46049       Zimbabwe                  NaN
46673       Zimbabwe                  NaN
35586       Zimbabwe                  NaN
71358       Zimbabwe                  NaN
44536       Zimbabwe               3600.0
31003       Zimbabwe               7200.0
24120       Zimbabwe                  NaN
19594       Zimbabwe                  NaN
45312       Zimbabwe                  NaN
30291       Zimbabwe              12000.0
71980       Zimbabwe              10800.0
27470       Zimbabwe                  NaN
64032       Zimbabwe              13200.0
52824       Zimbabwe                  NaN
43528       Zimbabwe                  NaN
36078       Zimbabwe             568968.0
4719        Zimbabwe                  NaN
42449       Zimbabwe                  NaN
59418       Zimbabwe              75000.0
72145       Zimbabwe                  NaN
25845       Zimbabwe                  NaN
30391       Zimbabwe                  NaN
25819       Zimbabwe                  NaN
3150          Zambia                  NaN
33910         Zambia                  NaN
53578         Zambia                  NaN
68826         Zambia                  NaN
71737         Zambia               6612.0
52282         Zambia                  NaN
19021         Zambia                  NaN
54532         Zambia                  NaN
58550         Zambia                  NaN
32505         Zambia                  NaN
56594         Zambia                  NaN
34595         Zambia                  NaN
63276         Zambia                  NaN
17066         Zambia                  NaN
52509         Zambia              14400.0
28334         Zambia                  NaN
25825         Zambia               4344.0
27561         Zambia                  NaN
65120         Zambia                  NaN
36262         Zambia                  NaN

In [52]:
ds.sort_values(by=['Country', 'ConvertedCompYearly'],ascending=[True, False], inplace= True)
ds[['Country', 'ConvertedCompYearly']].head(50)

                Country  ConvertedCompYearly
ResponseId
38513       Afghanistan             158484.0
43640       Afghanistan              92448.0
6892        Afghanistan              15600.0
43691       Afghanistan              13212.0
2449        Afghanistan              10894.0
6243        Afghanistan               5280.0
23224       Afghanistan               5280.0
55666       Afghanistan               2400.0
49274       Afghanistan               1634.0
42871       Afghanistan                  NaN
1960        Afghanistan                  NaN
70466       Afghanistan                  NaN
10234       Afghanistan                  NaN
15608       Afghanistan                  NaN
51548       Afghanistan                  NaN
55394       Afghanistan                  NaN
67667       Afghanistan                  NaN
55310       Afghanistan                  NaN
67566       Afghanistan                  NaN
3642        Afghanistan                  NaN
13852       Afghanistan                  NaN
53961       Afghanistan                  NaN
46026       Afghanistan                  NaN
60626       Afghanistan                  NaN
34044       Afghanistan                  NaN
48960       Afghanistan                  NaN
60650       Afghanistan                  NaN
23162       Afghanistan                  NaN
42123       Afghanistan                  NaN
33429       Afghanistan                  NaN
22877       Afghanistan                  NaN
61936       Afghanistan                  NaN
21766       Afghanistan                  NaN
10911       Afghanistan                  NaN
33329       Afghanistan                  NaN
71716       Afghanistan                  NaN
32133       Afghanistan                  NaN
30851       Afghanistan                  NaN
3776        Afghanistan                  NaN
61768       Afghanistan                  NaN
4503        Afghanistan                  NaN
28435       Afghanistan                  NaN
3887        Afghanistan                  NaN
6777        Afghanistan                  NaN
58078       Afghanistan                  NaN
25963       Afghanistan                  NaN
60517       Afghanistan                  NaN
17470       Afghanistan                  NaN
17039       Afghanistan                  NaN
56267       Afghanistan                  NaN

In [60]:
ds['ConvertedCompYearly'].nlargest(10)

ResponseId
40305    50000000.0
202      44790396.0
62027    35000000.0
70523    32500000.0
61044    28853768.0
62224    22500000.0
18923    22500000.0
66496    18000000.0
24164    15000000.0
1291     15000000.0
Name: ConvertedCompYearly, dtype: float64

In [62]:
ds.nlargest(10,'ConvertedCompYearly')
#OR
#ds.nsmallest(10,'ConvertedCompYearly')

,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
40305,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Full in-person,Freelance/contract work,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Blogs;Stack Overflow;Online books;Video-based ...,NaN,Less than 1 year,2,"Engineer, data;Engineer, site reliability;Deve...","5,000 to 9,999 employees",I have a great deal of influence,Other (please specify):;Visit developer commun...,United Kingdom of Great Britain and Northern I...,USD\tUnited States dollar,1000000.0,Weekly,APL;Assembly;Bash/Shell;C;C#;C++;COBOL;Crystal...,NaN,Cassandra;Couchbase;CouchDB;Cloud Firestore;Dy...,NaN,AWS;Colocation;Firebase;Google Cloud;Heroku;IB...,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core ;Blazo...,NaN,.NET;Apache Kafka;Capacitor;Cordova;Electron;F...,NaN,Ansible;Chef;Docker;Flow;Homebrew;Kubernetes;n...,NaN,Android Studio;Atom;CLion;Eclipse;Emacs;GoLand...,NaN,Other (please specify):,Linux-based;macOS;Windows;Windows Subsystem fo...,Git;Other (please specify):;Mercurial;SVN,Code editor;Command-line;Version control hosti...,NaN,NaN,Adobe Workfront;Airtable;Asana;Cerri;ClickUp;C...,NaN,Cisco Webex Teams;Coolfire Core;Google Chat;Ma...,NaN,Very favorable,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,Prefer not to say,Prefer not to say,Prefer not to say,Central Asian,Prefer not to say,Prefer not to say,Yes,Independent contributor,11.0,Agree,Agree,Agree,Agree,Agree,Agree,Agree,10+ times a week,3-5 times a week,6-10 times a week,60-120 minutes a day,60-120 minutes a day,Very long,Innersource initiative;DevOps function;Develop...,Yes,Yes,Yes,Appropriate in length,Easy,50000000.0
202,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Bootstrapping a business,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;edX,9,6,"Developer, front-end","10,000 or more employees",I have some influence,Start a free trial;Visit developer communities...,Portugal,EUR European Euro,42000044.0,Yearly,JavaScript;TypeScript,JavaScript;TypeScript,MariaDB;MongoDB,MongoDB,AWS;Firebase,AWS,Angular;Node.js;React.js;Svelte,Angular;Gatsby;Next.js;Node.js;React.js;Svelte...,NaN,NaN,npm,Ansible;Docker;Kubernetes;npm;Terraform,Visual Studio Code,Visual Studio Code,macOS;Windows,macOS;Windows,Git,Code editor;Command-line,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Cisco Webex Teams,Slack,Very favorable,Collectives on Stack Overflow;Stack Overflow;S...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,25-34 years old,Woman,No,Straight / Heterosexual,White;European;Hispanic or Latino/a,I am blind / have difficulty seeing,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,2.0,Strongly agree,Strongly agree,Neither agree nor disagree,Agree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,Less than 15 minutes a day,Somewhat long,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,44790396.0
62027,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Written Tutorials;Video-based Online Courses;O...,NaN,6,1,"Developer, front-end;Developer, full-stack;Dev...",10 to 19 employees,I have little or no influence,NaN,United States of America,USD\tUnited States dollar,700000.0,Weekly,Bash/Shell;Go;JavaScript;TypeScript,Bash/Shell;Go;JavaScript;Python;TypeScript,Elasticsearch;PostgreSQL,CouchDB;DynamoDB;Elasticsearch;MongoDB;MySQL;N...,NaN,NaN,Node.js;React.js;Vue.js,Node.js;React.js;Svelte;Vue.js,NaN,NaN,Docker,Docker;Kubernetes;Terraform;Unity 3D;Unreal En...,Visual Studio Code,NaN,Linux-based;Windows;Windows Subsystem for Linu...,Linux-based;Windows;Windows Subsystem for Linu...,Git,Command-line;Dedicated version control GUI app...,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Stack Overflow;Stack Exchange,A few times per week,No,NaN,"No, not really",18-24 years old,Man,No,Straight / Heterosexual,Asian,None of the above,None of the above,Yes,Independent contributor,1.0,Neither agree nor disagree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,Somewhat long,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Neither easy nor difficult,35000000.0
70523,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Freel...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy;Pluralsight;Udacity;Other,22,10,"Engineer, site reliability;DevOps specialist;C...","1,000 to 4,999 employees",I have a great deal of influence,Other (please specify):;Start a free trial;Vis...,United States of America,USD\tUnited States dollar,650000.0,Weekly,Bash/Shell;Go;JavaScript;Python;SQL,Bash/Shell;Go;JavaScript;Python;SQL,DynamoDB;Microsoft SQL Server;MySQL;PostgreSQL...,DynamoDB;PostgreSQL;Redis,AWS;Google Cloud;Heroku;Linode,AWS;Google Cloud;Heroku;Linode;Microsoft Azure,Angular;Angular.js;Node.js,Angular;Angular.js;Node.js,Apache Kafka;Apache Spark;Hadoop;NumPy;TensorFlow,Apache Kafka;Apache Spark;NumPy;TensorFlow,Docker;Kubernetes;npm;Terraform,Docker;Kubernetes;npm;Terraform,Vim;Visual Studio Code,Emacs;Vim;Visual Studio Code,Linux-based,Linux-based,Git,Command-line;Version control hosting service w...,NaN,NaN,Confluence;Jira Work Management;Notion;Trello,ClickUp;Confluence;Jira Work Management;Notion...,Google Chat;Slack;Zoom,Google Chat;Slack,Favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Not sure/can't remember,NaN,Neutral,35-44 years old,Man,No,Straight / Heterosexual,European;Central American;Hispanic or Latino/a,None of the above,I have autism / an autism spectrum disorder (e...,Yes,Independent contributor,16.0,Strongly agree,Disagree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Disagree,1-2 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,Less than 15 minutes a day,Somewhat short,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Easy,32500000.0
61044,I am a developer by profession,I prefer not to say,NaN,NaN,Primary/elementary school,On the job training;Online Courses or Certific...,NaN,Skillsoft,Less than 1 year,Less than 1 year,NaN,"Just me - I am a freelancer, sole proprietor, ...",I have little or no influence,Start a free trial;Visit developer communities...,Thailand,THB\tThai baht,985692510.0,Yearly,Go;HTML/CSS;Java;JavaScript;Objective-C;Swift;...,APL;Go;HTML/CSS;Java;JavaScript;Objective-C;Sw...,Cassandra;PostgreSQL,Cassandra;PostgreSQL,AWS,AWS,NaN,NaN,.NET,.NET,Ansible,Ansible,Android Studio,Android Studio,Other (please specify):,Other (please specify):,Other (please specify):,Code editor;Command-line;Version control hosti...,NaN,NaN,NaN,NaN,NaN,NaN,Unsure,Stack Overflow,Daily or almost daily,Yes,A few times per month or weekly,"No, not at all",25-34 years old,Man,Yes,Straight / Heterosexual,Prefer not to say,I am deaf / hard of hearing;I am unable to / f...,Prefer not to say,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,28853768.0
62224,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Friend or family member;Other online resources...,Technical documentation;Blogs;Stack Overflow;O...,NaN,15,10,"Developer, back-end;Cloud infrastructure engineer","5,000 to 9,999 employees",I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,450000.0,Weekly,Bash/Shell;HTML/CSS;Java;JavaScript;Python;Sca...,Go;Java;Python;Scala;SQL,Cassandra;DynamoDB;Elasticsearch;MySQL;Redis,Cassandra;Elasticsearch;MySQL;Redis,AWS,AWS;Google Cloud,Django;FastAPI;Flask;Node.js;React.js;Vue.js,Django;Flask;Node.js,Apache Kafka;Spring,Apache Kafka;Hadoop;Spring,Chef;Docker;Homebrew,Docker;Homebrew;Kubernetes;Terraform,IntelliJ;Vim,IntelliJ;Vim,macOS,Linux-based;macOS;Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Airtable;Confluence;Jira Work Management;Trello,Airtable;Confluence;Jira Work Management;Stack...,Slack;Zoom,Slack;Zoom,Favorable,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,"Yes, definitely",25-34 years old,Man,No,Queer,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,22500000.0
18923,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,NaN,Coursera;edX;Udacity,36,21,"Engineer, data;Developer, back-end;Cloud infra...","1,000 to 4,999 employees",I have little or no influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,450000.0,Weekly,Python;Scala,NaN,DynamoDB;PostgreSQL,NaN,AWS,NaN,NaN,NaN,NumPy;Pandas,NaN,NaN,NaN,IntelliJ;RStudio,NaN,NaN,Windows,Git,Dedicated version control GUI application,NaN,NaN,Jira Work Management,NaN,Cisco Webex Teams;Google Chat;Slack,NaN,Very favorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a;Indigenous (such as Nativ...,None of the above,I have autism / an autism spectrum disorder (e...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,22500000.0
66496,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Other,8,6,"Developer, back-end;DevOps specialist",100 to 499 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,360000.0,Weekly,Bash/Shell;Go;HTML/CSS;JavaScript;Python;Ruby;SQL,Bash/Shell;Go;HTML/CSS;JavaScript;Python;SQL,MongoDB;PostgreSQL;Redis,MongoDB;PostgreSQL;Redis,AWS,AWS,Next.js;Node.js;Ruby on Rails,Node.js,Apache Kafka,Apache Kafka;TensorFlow;Torch/PyTorch,Ansible;Chef;Docker;Homebrew;Kubernetes;npm;Te...,Ansible;Docker;Homebrew;Kubernetes;npm,Vim,Vim,macOS,Linux-based;macOS;Windows,Git,Command-line;Version control hosting service w...,NaN,NaN,Asana;Notion,Notion,RingCentral;Slack;Zoom,RingCentral;Slack;Zoom,Very unfavorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"No, not really",25-34 years old,Man,No,Straight / Heterosexual,Asian,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,18000000.0
24164,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Freelance/contract work,Some college/university study without earning ...,Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,12,10,NaN,"1,000 to 4,999 employees",I have some influence,Ask developers I know/work with,United States of America,USD\tUnited States dollar,300000.0,Weekly,JavaScript;Ruby;SQL,Crystal;Elixir,MySQL;Redis,NaN,AWS;Microsoft Azure,NaN,jQuery;Ruby on Rails,Phoenix,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Yarn,Unreal Engine,Neovim;Vim;Visual Studio Code,Android Studio,macOS,Linux-based,Git,Command-line,NaN,NaN,NaN,NaN,Microsoft Teams;Slack;Zoom,NaN,Very unfavorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"No, not really",35-44 years old,Man,No,Straight / Heterosexual,Caribbean;Hispanic or Latino/a,None of the above,I have a concentration and/or memory disorder ...,Yes,Independent contributor,22.0,Agree,Agree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,No,Appropriate in length,Easy,15000000.0
1291,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Other doctoral degree (Ph.D., Ed.D., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Coursera;Pluralsight;edX,10,5,Data scientist or machine learning specialist;...,"10,000 or more employees",I have a great deal of influence,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,300000.0,Weekly,Python,NaN,MongoDB,MongoDB;MySQL;SQLite,AWS;Microsoft Azure,Microsoft Azure,NaN,NaN,Keras;NumPy;Pandas;Qt;Scikit-learn;TensorFlow;...,NaN,NaN,NaN,IPython/Jupyter;Visual Studio Code,NaN,Windows,Linux-based;Windows,Git,Command-line;Dedicated version control GUI app...,NaN,NaN,Confluence;Jira Work Management;Notion,NaN,Microsoft Teams;Slack;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,15000000.0

In [68]:
df1= ds.nlargest(10,'ConvertedCompYearly')
df1[['ConvertedCompYearly','Country','MainBranch','Employment','DevType']]

,ConvertedCompYearly,Country,MainBranch,Employment,DevType
ResponseId,,,,,
40305,50000000.0,United Kingdom of Great Britain and Northern I...,I am a developer by profession,"Independent contractor, freelancer, or self-em...","Engineer, data;Engineer, site reliability;Deve..."
202,44790396.0,Portugal,I am a developer by profession,"Employed, full-time","Developer, front-end"
62027,35000000.0,United States of America,I am a developer by profession,"Employed, full-time","Developer, front-end;Developer, full-stack;Dev..."
70523,32500000.0,United States of America,I am a developer by profession,"Independent contractor, freelancer, or self-em...","Engineer, site reliability;DevOps specialist;C..."
61044,28853768.0,Thailand,I am a developer by profession,I prefer not to say,NaN
62224,22500000.0,United States of America,I am a developer by profession,"Employed, full-time","Developer, back-end;Cloud infrastructure engineer"
18923,22500000.0,United States of America,I am a developer by profession,"Employed, full-time","Engineer, data;Developer, back-end;Cloud infra..."
66496,18000000.0,United States of America,I am a developer by profession,"Employed, full-time","Developer, back-end;DevOps specialist"
24164,15000000.0,United States of America,I am a developer by profession,"Employed, full-time",NaN
1291,15000000.0,United States of America,I am a developer by profession,"Employed, full-time",Data scientist or machine learning specialist;...